# Generated by Django 2.2.28 on 2023-01-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_nacio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
