# Generated by Django 2.2.28 on 2023-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20230106_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_nacio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fotografia',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='fotos'),
        ),
    ]
