# Generated by Django 2.2.28 on 2023-01-11 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20230111_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_nacio',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
